import { StyleSheet } from "react-native";
import { C, F } from "@/lib/theme";
export const es = StyleSheet.create({
  lead: { color: C.dim, marginTop: 8, marginBottom: 20 },
  label: {
    fontFamily: F.sansBold,
    fontWeight: "600",
    fontSize: 15,
    color: C.ink,
    marginTop: 16,
    marginBottom: 8,
  },
  input: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.rule,
    padding: 12,
    color: C.ink,
    fontFamily: F.sans,
    fontSize: 16,
  },
  note: {
    fontFamily: F.sans,
    fontSize: 13,
    lineHeight: 19,
    color: C.dim,
    marginVertical: 6,
  },
  heading: {
    fontFamily: F.sansBold,
    fontSize: 21,
    fontWeight: "600",
    lineHeight: 27,
    color: C.ink,
    marginBottom: 8,
  },
  row: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  option: {
    minHeight: 44,
    padding: 12,
    borderRadius: 12,
    backgroundColor: C.land,
    justifyContent: "center",
  },
  on: { backgroundColor: C.ochreSoft, borderWidth: 1, borderColor: C.ochre },
  optionText: { color: C.ink, fontFamily: F.sansMedium, fontSize: 14 },
  error: { fontSize: 14, lineHeight: 20, color: C.rust, marginVertical: 12 },
  status: {
    fontSize: 12,
    fontWeight: "600",
    color: C.ochre,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  hash: { fontFamily: F.mono, fontSize: 11, lineHeight: 17, color: C.dim },
  balance: {
    fontSize: 36,
    fontWeight: "600",
    color: C.ink,
    marginVertical: 10,
  },
  rule: {
    borderTopWidth: 1,
    borderTopColor: C.rule,
    paddingTop: 12,
    marginTop: 12,
  },
  tabs: { flexDirection: "row", gap: 8, marginBottom: 20 },
});
