// API contract consumed by web/ (Next.js) and app/ (Expo). Source of truth is the pydantic models in
// api/; this file is GENERATED by `npx openapi-typescript http://localhost:8000/openapi.json -o
// shared/api.d.ts` and checked in so both apps build offline. Shown hand-written here as the sketch.
// Base URL: EXPO_PUBLIC_API_URL / NEXT_PUBLIC_API_URL = the stable tunnel (https://benmac.<tailnet>.ts.net).

export type Provenance = "known" | "estimated" | "missing";
export type Band = "target" | "acceptable" | "not_acceptable";
export type Actor = "lead" | "intake" | "appetite" | "hazard" | "portfolio" | "challenger" | "system" | "human" | "applicant";

export interface FactView {
  id: string;                 // "premium"
  label: string;              // "Total premium"
  display: string;            // "$41K-$78K (est.)" | "$2,073,000" | "missing"
  provenance: Provenance;
  source: string;             // "median technical_premium/TIV of 9 bound property comparables"
  resolver?: "broker" | "intake" | "hazard" | "portfolio" | "applicant";
}

export interface FactorView { fact: string; possible: Band[]; valueText: string; provenance: Provenance }
export interface Interval { lo: number; hi: number }

export type DecisionView =
  | { kind: "accept" | "refer" | "decline" | "approve"; because: string[]; by: "desk" | "human" }
  | { kind: "open"; straddles: number; flippers: { fact: string; resolver: string }[] }
  | { kind: "routed"; to: string; because: string };

/** A human's bounded adjustment of the engine's interval (docs/OVERRIDE.md). It never replaces the
 *  engine's numbers: `engineScore`/`engineDecision` are the desk's, `score`/`decision` the human's. */
export interface CaseOverride {
  points: number;                       // signed, at most ±bound
  reason: string;
  by: string;                           // "underwriter"
  at: number;                           // epoch seconds
  bound: number;                        // 5, a product decision (api/src/atlas_api/override.py)
  provenance: "human";
  engineScore: Interval;
  engineDecision: DecisionView;
  score: Interval;
  decision: { kind: string; because: string[]; by: "human" };
}

export interface QueueRow {
  caseId: string; insured: string; line: string; state: string; status: string;
  score: Interval | null; decision: DecisionView; valueAtStake: number;   // null when no guideline scores this row
  issues: { kind: string; severity: "info" | "warn" | "block" }[];
  deepDived: boolean; enrichmentDelta: number | null;   // midpoint with minus without external layers
  override?: CaseOverride;
}

export interface RiskFactorView { peril: string; line: string; applied: number; capped: boolean; source: string; citation: string }

export interface CaseView {
  caseId: string; kind: "commercial" | "tenant"; title: string;
  facts: FactView[]; factors: FactorView[];
  score: Interval | null; scoreWithoutEnrichment: Interval | null; decision: DecisionView;
  risk: { factors: RiskFactorView[]; total: number; totalCapped: boolean; skipped: [string, string][] };
  portfolio?: { line: string; points: number; neighbourhoodTiv: number; threshold: number };
  contradictions: { good: string[]; bad: string[]; resolve: string[] }[];
  explanation: string; explanationVerified: boolean;
  issues: { kind: string; severity: string; text: string }[];
  actions: { key: string; channel: string; status: string; at: string }[];
  override?: CaseOverride;
  surroundings?: { summary: string; places: { name: string; url: string }[] };
  site: { lat: number; lng: number };
}

export interface DeskEvent {
  id: string; caseId: string; runId?: string; seq: number; tMs: number;
  actor: Actor; kind: string; to?: Actor; inReplyTo?: string;
  body: Record<string, unknown>; refs: string[];
}

export interface Hex { cell: string; ring: [number, number][]; value: number; level: 0 | 1 | 2 | 3 | 4 }

export interface AskResult {
  question: string; rationale: string;
  attempts: { payload: unknown; lint: string[]; error?: string; rows: number }[];
  finalPayload: unknown; columns: string[]; rows: Record<string, unknown>[]; answer: string; runId: string;
}

export interface BacktestView { /* mirrors proof.BacktestReport, camelCased */ [k: string]: unknown }

export interface TenantRequest {
  address?: string; lat?: number; lng?: number;
  answers: { contentsValue: number; unitLevel: "basement" | "ground" | "upper"; claims3yr: number; deductible: 500 | 1000 | 2500 };
}

export interface QuoteView {
  caseId: string;                          // "TQ-7f3a": a real case in the same store
  decision: { kind: "approve" | "refer"; reasons: string[]; nextStep: string };
  annual: number; monthly: number; label: "Illustrative. Our documented model, not an Intact price or offer.";
  receipt: { lines: { label: string; multiplier: number; dollars: number; capped: boolean; source: string }[]; base: number };
  recommendations: { addOn: string; why: string }[];   // e.g. sewer backup: basement unit + study area
  hexes: Hex[]; center: [number, number];
  listSummary: string;                     // the full non-map path, screen-reader first
  underwriterUrl: string;                  // https://<web>/cases/TQ-7f3a
}

// Endpoints (FastAPI). Every GET is served from cache when ATLAS_OFFLINE=1.
export const routes = {
  queue: "GET /queue?view=open|all",                    // QueueRow[]
  case: "GET /cases/{id}",                              // CaseView
  events: "GET /cases/{id}/events?replay=0|1&speed=1",  // SSE of DeskEvent
  runDesk: "POST /desk/run {caseIds?, mode}",           // {runId}
  ask: "POST /ask {question}",                          // AskResult (streams Intake events on /runs/{runId}/events)
  backtest: "GET /backtest",                            // BacktestView
  mapBook: "GET /map/book?res=5&peril=",                // Hex[] of active TIV
  mapTenant: "GET /map/toronto?lat&lng&k=3",            // Hex[] break-ins (shrunk)
  quote: "POST /quote/tenant",                          // QuoteView
  override: "POST /cases/{id}/override {points, reason}", // CaseOverride; DELETE undoes it
  health: "GET /health",                                // Sentry uptime monitor target
} as const;
